---
- name: Create OpenShift namespace
  hosts: localhost
  connection: local

  tasks:
  - name: clone repo
    ansible.builtin.git:
      repo: 'https://github.com/joshuacanter/namespace-demo.git'
      dest: /tmp/{{ namespace }}

  - name: create values folder
    ansible.builtin.file:
      path: /tmp/{{ namespace }}/clusters/configuration/{{ cluster }}/namespace-config/{{ namespace }}
      state: directory

  - name: create values from template
    ansible.builtin.template:
      src: templates/values.yaml.j2
      dest: /tmp/{{ namespace }}/clusters/configuration/{{ cluster }}/namespace-config/{{ namespace }}/values.yaml

  - name: create argo application folder
    ansible.builtin.file:
      path: /tmp/{{ namespace }}/clusters/applications/{{ cluster }}/namespace-config/{{ namespace }}
      state: directory

  - name: create argo application from template
    ansible.builtin.template:
      src: templates/application.yaml.j2
      dest: /tmp/{{ namespace }}/clusters/applications/{{ cluster }}/namespace-config/{{ namespace }}/application.yaml

  - name: Check new files into git
    ansible.builtin.shell: |
      git checkout -b {{ namespace }}-create
      git status
      git add clusters/*
      git commit -m "Create {{ namespace }}"
      git remote set-url origin https://{{ user }}:{{ token }}@github.com/joshuacanter/namespace-demo.git
      git push --set-upstream origin {{ namespace }}-create
    args:
      chdir: "/tmp/{{ namespace }}"

  - name: open pr
    ansible.builtin.uri:
      url: https://api.github.com/repos/joshuacanter/namespace-demo/pulls
      method: POST
      body: 
        title: "{{ namespace }} creation"
        body: Initial creation of {{ namespace }}
        head: "{{ namespace }}-create"
        base: main
      body_format: json
      headers:
        Accept: application/vnd.github+json
        X-GitHub-Api-Version: 2022-11-28
        Authorization: Bearer {{ token }}
      status_code: 201


